version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
      DB_HOST: "postgres"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    image: postgres:16-alpine
    ports:
      - '${POSTGRES_PORT}:5432'
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure
