# Generated by Django 5.1.6 on 2025-03-28 19:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allergy", "0003_remove_symptomrecord_entry_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medications",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("medication_name", models.CharField(max_length=255)),
                (
                    "medication_type",
                    models.CharField(
                        choices=[
                            ("pills", "Pills"),
                            ("injection", "Injection"),
                            ("eye_drops", "Eye Drops"),
                            ("nose_drops", "Nose Drops"),
                        ],
                        max_length=255,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "medication_name", "medication_type")},
            },
        ),
    ]
