# Generated by Django 5.2 on 2025-04-13 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("allergy", "0004_medications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Medications",
            new_name="Medication",
        ),
    ]
