# Generated by Django 6.0.3 on 2026-03-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allergy", "0005_rename_medications_medication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="medication_type",
            field=models.CharField(
                choices=[
                    ("pills", "Pills"),
                    ("injection", "Injection"),
                    ("eye_drops", "Eye Drops"),
                    ("nasal_spray", "Nasal Spray"),
                    ("inhaler", "Inhaler"),
                    ("syrup", "Syrup"),
                ],
                max_length=255,
            ),
        ),
    ]
